### ISSUE TITLE
NSG UE Capability Information import returns undefined ID

### ISSUE THREAD

**Issue by High3eam** [HandyMenny/uecapabilityparser#196]
Version: [da49cf1](https://github.com/HandyMenny/uecapabilityparser/commit/da49cf1bc6b268b2b3b0d95b03d9cc4af382c2c9)

UE Capabilities Testfile: [xiaomi12tpro_nruecaps-sa.txt](https://github.com/HandyMenny/uecapabilityparser/files/11584769/xiaomi12tpro_nruecaps-sa.txt)

Choosing NSG UE Capabilities as Import option returns undefined ID, both with pasting manually and uploading a file. No combos displayed for the log.

Flags for the POST request after sending the message:

<details>
  <summary>HTTP POST Params</summary>
<img src="https://github.com/HandyMenny/uecapabilityparser/assets/15855905/8d2e26e4-b551-4c2a-ad55-092fd1eb3b7f">
</details>

To reproduce:
<details>
  <summary>STEP 1</summary>
<img src="https://github.com/HandyMenny/uecapabilityparser/assets/15855905/d5c20d9a-5097-4090-b3d7-9f0e5756303e">
</details>

<details>
  <summary>STEP 2</summary>
<img src="https://github.com/HandyMenny/uecapabilityparser/assets/15855905/55d7e30a-af59-443c-b07c-250b881a2402">
</details>

**Comment by HandyMenny** [comment]
Thanks.
This is the stacktrace:

```
java.lang.NullPointerException: Cannot invoke "com.ericsson.mts.asn1.ASN1Parser$ReferencedTypeContext.definedType()" because the return value of "com.ericsson.mts.asn1.ASN1Parser$AsnTypeContext.referencedType()" is null
	at com.ericsson.mts.asn1.converter.ConverterNSG.parseSequenceOf(ConverterNSG.kt:166)
	at com.ericsson.mts.asn1.converter.AbstractConverter.processLines(AbstractConverter.kt:143)
	at com.ericsson.mts.asn1.converter.AbstractConverter.processLines$default(AbstractConverter.kt:96)
	at com.ericsson.mts.asn1.converter.ConverterNSG.parseSequenceOf(ConverterNSG.kt:219)
	at com.ericsson.mts.asn1.converter.AbstractConverter.processLines(AbstractConverter.kt:143)
	at com.ericsson.mts.asn1.converter.AbstractConverter.processLines$default(AbstractConverter.kt:96)
	at com.ericsson.mts.asn1.converter.AbstractConverter.convert(AbstractConverter.kt:68)
	at com.ericsson.mts.asn1.ASN1Converter.convert(ASN1Converter.kt:53)
```

So the issue is in my mts-asn1 fork. Do you have the hexdump?

**Comment by High3eam** [comment]
@HandyMenny Sure!
[ueCapsWithHex.txt](https://github.com/HandyMenny/uecapabilityparser/files/11584894/ueCapsWithHex.txt)

**Comment by HandyMenny** [comment]
The hexdump is parsed correctly, so the problem is in the converter for NSG: https://uecapability.smartphonecombo.it/view/?id=b08f5dea-a7cf-4337-bd82-e07c2d0d38f8
